# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # Maven dependencies
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Check for security updates daily
    open-pull-requests-limit: 20
    target-branch: "master"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "security"
      include: "scope"
  
  # Additional Maven modules
  - package-ecosystem: "maven"
    directory: "/spotless-maven-plugin"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "security"
      - "spotless-plugin"
    commit-message:
      prefix: "security"
      include: "scope"
  
  # GraphRAG Python dependencies
  - package-ecosystem: "pip"
    directory: "/graphrag"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "master"
    labels:
      - "dependencies"
      - "security"
      - "python"
    commit-message:
      prefix: "security"
      include: "scope"


