# POM Audit - Maven Build Workflow for kiva

name: Maven Build - kiva

on:
  push:
    branches: [ "master", "main", "develop" ]
    paths:
      - 'kiva/**'
      - 'kiva/pom.xml'
  pull_request:
    branches: [ "master", "main", "develop" ]
    paths:
      - 'kiva/**'
      - 'kiva/pom.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build kiva
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build kiva
      run: mvn -B clean install -DskipTests -fn
      working-directory: kiva
      env:
        MAVEN_OPTS: '-Xmx2048m -Xms1024m'
        
    - name: Run tests for kiva
      run: mvn -B test -fn
      working-directory: kiva
      continue-on-error: true
      env:
        MAVEN_OPTS: '-Xmx2048m -Xms1024m'
        
    - name: Generate dependency tree
      run: mvn dependency:tree -DoutputFile=dependency-tree.txt
      working-directory: kiva
      continue-on-error: true
      
    - name: Upload dependency tree
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-tree-kiva
        path: kiva/dependency-tree.txt
        retention-days: 30